---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: dummy-service
spec:
    replicas: 3
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 50%
            maxSurge: 50%
    selector:
        matchLabels:
            app: dummy-service
    template:
        metadata:
            labels:
                app: dummy-service
                tier: backend
                track: stable
        spec:
            containers:
                - name: dummy-service
                  image: jackdavies606/dummy-service:v4
                  ports:
                  - containerPort: 8080
                  livenessProbe:
                      initialDelaySeconds: 10
                      timeoutSeconds: 15
                      httpGet:
                        path: /actuator/health
                        port: 8080
                  readinessProbe:
                      initialDelaySeconds: 10
                      timeoutSeconds: 15
                      httpGet:
                        path: /actuator/health
                        port: 8080

#                                livenessProbe:
#                                    httpGet:
#                                        path: /actuator/health
#                                        port: 8080
#                                    initialTimeoutDelaySeconds: 10
#                                    timeoutSeconds: 15
#            readinessProbe:
#                httpGet:
#                    path: /actuator/health
#                    port: 8080
#                initialTimeoutDelaySeconds: 10
#                timeoutSeconds: 15
