---
kind: Deployment
apiVersion: apps/v1
metadata:
    name: dummy-service-canary
spec:
    replicas: 0
    selector:
        matchLabels:
            app: dummy-service
    template:
        metadata:
            labels:
                app: dummy-service
                tier: backend
                track: canary
        spec:
            containers:
                - name: dummy-service
                  image: jackdavies606/dummy-service:v4
                  ports:
                      - containerPort: 8080
                  livenessProbe:
                      initialDelaySeconds: 10
                      timeoutSeconds: 15
                      httpGet:
                          path: /actuator/health
                          port: 8080
                  readinessProbe:
                      initialDelaySeconds: 10
                      timeoutSeconds: 15
                      httpGet:
                          path: /actuator/health
                          port: 8080
