master:
    ServicePort: 8080
    serviceType: NodePort
    NodePort: 32123
    ScriptApproval:
        - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
        - "new groovy.json.JsonSlurperClassic"
        - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
        - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
    InstallPlugins:
        - kubernetes:1.6.4
        - workflow-aggregator:2.5
        - workflow-job:2.21
        - credentials-binding:1.16
        - git:3.9.1
agent:
    volumes:
        - type: HostPath
          hostPath: /var/run/docker.sock
          mountPath: /var/run/docker.sock

persistence:
    Enabled: true
    StorageClass: jenkins-volume
    Size: 10Gi

networkPolicy:
    Enabled: false
    apiVersion: extensions/v1beta1
