---
apiVersion: v1
kind: Service
metadata:
    name: dummy-service
spec:
    type: NodePort
    selector:
        app: dummy-service
        tier: backend
    ports:
        - protocol: TCP
          port: 8080
          nodePort: 30623
